name: Dify Workflow Automation

on:
  schedule:
    - cron: "0 1 * * *" # 北京时间上午09:00（UTC 01:00）
  workflow_dispatch: # 支持手动触发

env:
  DIFY_API_KEY: ${{ secrets.DIFY_API_KEY }}
  DIFY_BASE_URL: ${{ secrets.DIFY_BASE_URL }}
  DIFY_WORKFLOW_ID: ${{ secrets.DIFY_WORKFLOW_ID }}

jobs:
  trigger-dify-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 安装依赖
        run: |
          npm install axios

      - name: 触发 Dify 工作流
        run: |
          node <<EOF
          const axios = require('axios');
          
          async function triggerWorkflow() {
            try {
              const response = await axios.post(
                \`\${process.env.DIFY_BASE_URL}/workflow/trigger\`,
                {
                  workflow_id: process.env.DIFY_WORKFLOW_ID,
                  parameters: {} // 可根据需要添加参数
                },
                {
                  headers: {
                    'Content-Type': 'application/json',
                    'Authorization': \`Bearer \${process.env.DIFY_API_KEY}\`
                  }
                }
              );
              
              console.log('工作流触发成功:', response.data);
              return response.data;
            } catch (error) {
              console.error('工作流触发失败:', error.message);
              if (error.response) {
                console.error('状态码:', error.response.status);
                console.error('错误详情:', error.response.data);
              }
              throw error;
            }
          }
          
          triggerWorkflow()
            .then(data => {
              console.log('Dify 工作流执行成功');
              process.exit(0);
            })
            .catch(error => {
              console.error('Dify 工作流执行失败:', error);
              process.exit(1);
            });
          EOF
